import React from 'react';

const WordFetcher = () => {
  const words = [
    { spanish: 'hombre', swedish: 'man' },
    { spanish: 'hola', swedish: 'hej' },
    { spanish: 'chao', swedish: 'hejdå' },
    { spanish: 'adios', swedish: 'adjö' },
    { spanish: 'ahora', swedish: 'nu' },
    { spanish: 'ordenador', swedish: 'dator' },
    { spanish: 'celular', swedish: 'telefon' },
    { spanish: 'libro', swedish: 'bok' },
    { spanish: 'mujer', swedish: 'kvinna' },
    { spanish: 'mañana', swedish: 'imorgon' },
    { spanish: 'ayer', swedish: 'igår' },
    { spanish: 'desayuno', swedish: 'frukost' },
    { spanish: 'cena', swedish: 'middag' },
    { spanish: 'noche', swedish: 'kväll' },
    { spanish: 'dia', swedish: 'dag' },
    { spanish: 'hoy', swedish: 'idag' },
    { spanish: 'amigos', swedish: 'vänner' },
    { spanish: 'novia', swedish: 'flickvän' },
    { spanish: 'novio', swedish: 'pojkvän' },
    { spanish: 'cancion', swedish: 'sång' },
    { spanish: 'mundo', swedish: 'värld' },
    { spanish: 'trabajo', swedish: 'arbete' },
    { spanish: 'escuela', swedish: 'skola' },
    { spanish: 'boxeo', swedish: 'boxning' },
    { spanish: 'cama', swedish: 'säng' },
    { spanish: 'mesa', swedish: 'bord' },
    { spanish: 'perro', swedish: 'hund' },
    { spanish: 'gato', swedish: 'katt' },
    { spanish: 'mono', swedish: 'apa' },
    { spanish: 'pez', swedish: 'fisk' },
    { spanish: 'pajaro', swedish: 'fågel' },
    { spanish: 'uno', swedish: 'ett' },
    { spanish: 'dos', swedish: 'två' },
    { spanish: 'tres', swedish: 'tre' },
    { spanish: 'cuatro', swedish: 'fyra' },
    { spanish: 'cinco', swedish: 'fem' },
    { spanish: 'seis', swedish: 'sex' },
    { spanish: 'siete', swedish: 'sju' },
    { spanish: 'ocho', swedish: 'åtta' },
    { spanish: 'nueve', swedish: 'nio' },
    { spanish: 'diez', swedish: 'tio' },
    { spanish: 'lampara', swedish: 'lampa' },
    { spanish: 'cucaracha', swedish: 'kackerlacka' },
    { spanish: 'estrella', swedish: 'stjärna' },
    { spanish: 'papa', swedish: 'potatis' },
    { spanish: 'padre', swedish: 'fader' },
    { spanish: 'madre', swedish: 'moder' },
    { spanish: 'ensalada', swedish: 'sallad' },
    { spanish: 'pelo', swedish: 'hår' },
    { spanish: 'boca', swedish: 'mun' },
    { spanish: 'dedos', swedish: 'fingrar' },
    { spanish: 'manos', swedish: 'händer' },
    { spanish: 'agua', swedish: 'vatten' },
    { spanish: 'huevos', swedish: 'ägg' },
    { spanish: 'mariposa', swedish: 'fjäril' },
    { spanish: 'pelicula', swedish: 'film' },
    { spanish: 'harina', swedish: 'mjöl' },
    { spanish: 'niños', swedish: 'barn' },
    { spanish: 'niño', swedish: 'grabb' },
    { spanish: 'niña', swedish: 'tös' },
    { spanish: 'chica', swedish: 'flicka' },
    { spanish: 'chico', swedish: 'pojke' },
    { spanish: 'pais', swedish: 'land' },
    { spanish: 'ventana', swedish: 'fönster' }
  ];
  return words;
}
export default WordFetcher;
